+new staff and alphabetisise
ImpactDevelopment/ImpactIssues pull request #2743
Opened 2020-12-04 21:26 UTC by berrely

2020-12-04 23:25 UTC, l1ving approved these changes
lgtm, I'm not sure about the actual current staff so someone else has to merge

2020-12-04 23:42 UTC, CesiumCs commented on README.md
> -* Scandal Bot
i left the bots on the bottom on purpose, but i doubt there was any good reason to lol, so that can be left as you have it

2020-12-04 23:42 UTC, CesiumCs commented on README.md
> +* Skyklat
sky has a github with the same name, you can add it the same way the other githubs are linked

2020-12-04 23:42 UTC, CesiumCs commented
"alphabetisise"

2020-12-05 16:06 UTC, CesiumCs requested changes

2020-12-05 16:06 UTC, CesiumCs commented on README.md
> +* Skyklat
realized you managed to spell it wrong
skylykat

2020-12-05 16:09 UTC, berrely reviewed
Seems good

2020-12-05 18:41 UTC, elonmusksama commented
my pr is superior get owned berrely

2020-12-05 19:35 UTC, CesiumCs commented
Brit destroyed

2020-12-07 14:53 UTC, elonmusksama commented
#2744 solves this. @berrely

2020-12-07 15:08 UTC, CesiumCs commented
yes please close this useless pr

2020-12-07 15:30 UTC, closed without merging